### ISSUE TITLE
Complete VICOM 128 Requirements

### ISSUE THREAD

**Issue by progdawn** [progdawn/inksauce#12]
**Part I - Project Documents**
- [x] [Project Plan/Description](https://github.com/progdawn/progdawn.github.io/files/1516499/Final.Project.Plan.pdf)
- [x] [Project FlowChart/SiteMap](https://user-images.githubusercontent.com/14948999/33412698-c2161e66-d552-11e7-83f9-7a4128dcd1f3.png)
- [x] [Project Wireframes](https://user-images.githubusercontent.com/14948999/33412717-e71475d2-d552-11e7-872e-c6e3d21ca1fe.png)

**Part II - Web Site Beta**
_Images can be place holders_
_Some content can be missing_
- [x] HTML5 files for each page 
- [x] CSS code working
- [x] Minumum 15 CSS style rules
- [x] Navigation works
- [x] Minimum 5 pages
- [x] Contain content specific to the subject
- [x] Contains contact form
- [x] Contain at least one link to outside URL
- [x] Looks pro-fresh-ional (get it?)

**Part III - Test and Fix**   
- [x] Validate site with validator.w3.org for all pages, and turn in screenshots
- [x] Upload the website to the mca.matc.edu web server and test the functionality
- [x] Verify all links work
- [x] Verify form works and sends email
- [x] Fix all errors or make changes(updates) as needed

**Part IV - Final**
- [x] Complete website working with no errors
- [x] CSS working with no errors
- [x] All content included
- [x] Form works with no errors
- [x] Published to the web server

**Comment by progdawn** [comment]
Link to site submitted to Blackboard. Class complete!
